/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * About.java
 *
 * Created on 14-jul-2009, 10:47:20
 */

package nl.shadowlink.shadowmapper;

import javax.swing.*;
import java.awt.*;

/**
 * @author Kilian
 */
public class About extends JDialog {

	private static final String[] VALUES = new String[] { "Shadow-Mapper", "Beta 0.1.0", "31-12-2009" };

	private static final String[] PEOPLE_THANKS = new String[] { "Aru ", "DeXx  ", "JostVice", "Johnline", "OinkOink", "Paroxum  ", "REspawn  ",
			"supermortalhuman ", "Tim  ", "", "Everyone I forgot" };

	/**
     * Creates new form About
     * */
	public About() {
		this.setIconImage(java.awt.Toolkit.getDefaultToolkit().createImage("icon.png"));
		initComponents();

		// center the window
		Toolkit toolkit = Toolkit.getDefaultToolkit();
		Dimension screenSize = toolkit.getScreenSize();
		int x = (screenSize.width - this.getWidth()) / 2;
		int y = (screenSize.height - this.getHeight()) / 2;
		this.setLocation(x, y);

		setText(VALUES);
		this.setVisible(true);
	}

	public void setText(String[] values) {
		labelName.setText(values[0]);
		labelVersion.setText(values[1]);
		labelDate.setText(values[2]);
	}

	public void paintPanel(Graphics g) {
		for (int i = 0; i < PEOPLE_THANKS.length; i++) {
			g.drawString(PEOPLE_THANKS[i], 10, 10 + (i * 12));
		}
		this.repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel() {
			public void paint(Graphics g) {
				paintPanel(g);
			}
		};
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		labelName = new javax.swing.JLabel();
		labelVersion = new javax.swing.JLabel();
		labelDate = new javax.swing.JLabel();
		labelSL = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Shadow Mapper");
		setResizable(false);
		getContentPane().setLayout(new GridLayout());// new org.netbeans.lib.awtextra.AbsoluteLayout());

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 220, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 140, Short.MAX_VALUE));

		getContentPane().add(jPanel1);// , new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 220, 140));

		jLabel1.setText("Special Thanks");
		getContentPane().add(jLabel1);// , new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

		// jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_about.png"))); // NOI18N
		getContentPane().add(jLabel2);// , new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 110, 110));

		labelName.setText("program Name");
		getContentPane().add(labelName);// , new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

		labelVersion.setText("Version 1.0");
		getContentPane().add(labelVersion);// , new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

		labelDate.setText("01-01-2000");
		getContentPane().add(labelDate);// , new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

		labelSL.setText("©2009 - 2015 Shadow-Link");
		getContentPane().add(labelSL);// , new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

		jLabel3.setText("Website: http://www.Shadow-Link.nl");
		getContentPane().add(jLabel3);// , new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel labelDate;
	private javax.swing.JLabel labelName;
	private javax.swing.JLabel labelSL;
	private javax.swing.JLabel labelVersion;
	// End of variables declaration//GEN-END:variables

}
