/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoadingBar.java
 *
 * Created on 16-dec-2009, 11:33:03
 */

package nl.shadowlink.shadowmapper;

import nl.shadowlink.shadowgtalib.utils.Constants.GameType;
import nl.shadowlink.shadowmapper.FileManager.LoadingStatusChangedListener;
import javax.swing.*;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 * LoadingBar shows a loading bar to the user whilest Shadow-Mapper is loading the GTA-IV install
 *
 * @author Kilian
 */
public class LoadingBar extends JFrame implements LoadingStatusChangedListener {

	/** Reference to the FileManager */
	private FileManager mFileManager;

	/**
	 * Creates new form LoadingBar
	 */
	public LoadingBar(final String gameDir, final GameType pGameType, final byte[] key) {
		final Toolkit toolkit = Toolkit.getDefaultToolkit();
		setIconImage(toolkit.createImage("icon.png"));
		initComponents();
		setVisible(true);

		// center the window
		Dimension screenSize = toolkit.getScreenSize();
		int x = (screenSize.width - this.getWidth()) / 2;
		int y = (screenSize.height - this.getHeight()) / 2;
		this.setLocation(x, y);

		mFileManager = new FileManager(gameDir, pGameType, key);
		mFileManager.setLoadStatusChangedListener(this);
		startLoading();
	}

	/**
	 * Start loading the GTA install
	 */
	private void startLoading() {
		Thread queryThread = new Thread() {
			public void run() {
				mFileManager.load();
			}
		};
		queryThread.start();
	}

	@Override
	public void onMaxItemsToLoadChanged(final int pMaxItemsToLoad) {
		BarLoading.setMinimum(0);
		BarLoading.setValue(0);
		BarLoading.setMaximum(pMaxItemsToLoad);
	}

	@Override
	public void onLoadingStatusTextChanged(final String pLoadingStatusText) {
		labelLoading.setText(pLoadingStatusText);
	}

	@Override
	public void onLoadingProgressChanged(final int pLoadingProgress) {
		BarLoading.setValue(pLoadingProgress);
	}

	@Override
	public void onLoadingProgressIncreased() {
		BarLoading.setValue(BarLoading.getValue() + 1);
	}

	@Override
	public void onLoadingFailed() {
		// TODO: Show error
	}

	@Override
	public void onLoadingFinished() {
		// TODO: Open main screen
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		labelLoading = new javax.swing.JLabel();
		BarLoading = new javax.swing.JProgressBar();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setTitle("Loading");
		setResizable(false);

		labelLoading.setText("Loading: ");

		BarLoading.setStringPainted(true);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(BarLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 280,
														javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(labelLoading))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addGap(6, 6, 6)
						.addComponent(labelLoading)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(BarLoading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JProgressBar BarLoading;
	private javax.swing.JLabel labelLoading;
	// End of variables declaration//GEN-END:variables

}
